/* ptolemy.cg.kernel.generic.GenericCodeGenerator
Generated by Ptolemy II (http://ptolemy.eecs.berkeley.edu)
Copyright (c) 2005-2016 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.
IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS.
*/
#ifdef __cplusplus
extern "C" {
    #endif
    #include "DECGClockRamp_Display.h"
    #ifdef __cplusplus
}
#endif
/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
Variable declaration code */
/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
end variable declaration code */
#ifdef __cplusplus
extern "C" {
    #endif
    static struct TypedIOPort* input;
    void DECGClockRamp_Display_preinitialize(struct AtomicActor* actor);
    void DECGClockRamp_Display_initialize(struct AtomicActor* actor);
    bool DECGClockRamp_Display_prefire(struct AtomicActor* actor);
    void DECGClockRamp_Display_fire(struct AtomicActor* actor);
    bool DECGClockRamp_Display_postfire(struct AtomicActor* actor);
    void DECGClockRamp_Display_wrapup(struct AtomicActor* actor);
    struct AtomicActor* DECGClockRamp_Display_New() {
        struct AtomicActor* DECGClockRamp_Display = AtomicActor_New();
        #ifdef _debugging
        ((struct AtomicActor*)DECGClockRamp_Display)->setName((struct AtomicActor *)DECGClockRamp_Display, "Display");
        #endif
        DECGClockRamp_Display->container = DECGClockRamp;
        DECGClockRamp_Display->preinitialize = DECGClockRamp_Display_preinitialize;
        DECGClockRamp_Display->initialize = DECGClockRamp_Display_initialize;
        DECGClockRamp_Display->prefire = DECGClockRamp_Display_prefire;
        DECGClockRamp_Display->fire = DECGClockRamp_Display_fire;
        DECGClockRamp_Display->postfire = DECGClockRamp_Display_postfire;
        DECGClockRamp_Display->wrapup = DECGClockRamp_Display_wrapup;
        input = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        input->setName((struct IOPort*)input, "input");
        #endif
        input->container = (struct Actor*)DECGClockRamp_Display;
        input->_isInsideConnected = false;
        input->_isOutsideConnected = true;
        input->_isInput = true;
        input->_isOutput = false;
        input->_isMultiport = true;
        input->_width = 1;
        input->_insideWidth = 0;
        input->_numberOfSinks = 0;
        input->_numberOfSources = 1;
        input->_type = TYPE_Int;
        pblListAdd(DECGClockRamp_Display->_inputPorts, input);
        PblList* input_0 = pblListNewArrayList();
        struct DEReceiver* input_0_0 = DEReceiver_New();
        input_0_0->container = (struct IOPort*)input;
        input_0_0->_director = (struct DEDirector*)(*(DECGClockRamp_Display->getDirector))(DECGClockRamp_Display);
        pblListAdd(input_0, input_0_0);
        pblListAdd(input->_localReceivers , input_0);
        return DECGClockRamp_Display;
    }
    struct IOPort* DECGClockRamp_Display_get_input() {
        return (struct IOPort*) input;
    }
    void DECGClockRamp_Display_preinitialize(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Preinitalization of the actor : DECGClockRamp_Display */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the preinitalization of the actor : DECGClockRamp_Display */
    void DECGClockRamp_Display_initialize(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Initalization of the actor : DECGClockRamp_Display */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the initalization of the actor : DECGClockRamp_Display */
    bool DECGClockRamp_Display_prefire(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        prefire of the actor : DECGClockRamp_Display */
        return true;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the prefire of the actor : DECGClockRamp_Display */
    #ifdef __cplusplus
}
#endif
void DECGClockRamp_Display_fire(struct AtomicActor* actor) {
    if ((*(input->hasToken))((struct IOPort*) input, 0)) {
        printf("%d\n", (*(input->get))((struct IOPort*) input, 0)->payload.Int);
    }
}
#ifdef __cplusplus
extern "C" {
    #endif
    bool DECGClockRamp_Display_postfire(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Postfire of the actor : DECGClockRamp_Display */
        return true;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the postfire of the actor : DECGClockRamp_Display */
    void DECGClockRamp_Display_wrapup(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Wrapup of the actor : DECGClockRamp_Display */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the wrapup of the actor : DECGClockRamp_Display */
    #ifdef __cplusplus
}
#endif
