/* ptolemy.cg.kernel.generic.GenericCodeGenerator
Generated by Ptolemy II (http://ptolemy.eecs.berkeley.edu)
Copyright (c) 2005-2016 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.
IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS.
*/
#ifdef __cplusplus
extern "C" {
    #endif
    #include "DECGMath_AddSubtract.h"
    #ifdef __cplusplus
}
#endif
/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
Variable declaration code */
/* ptolemy.cg.adapter.generic.program.procedural.adapters.ptolemy.actor.lib.AddSubtract
preinitialize AddSubtract */
int DECGMath_AddSubtract__result;
/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
end variable declaration code */
#ifdef __cplusplus
extern "C" {
    #endif
    static struct TypedIOPort* plus;
    static struct TypedIOPort* output;
    void DECGMath_AddSubtract_preinitialize(struct AtomicActor* actor);
    void DECGMath_AddSubtract_initialize(struct AtomicActor* actor);
    bool DECGMath_AddSubtract_prefire(struct AtomicActor* actor);
    void DECGMath_AddSubtract_fire(struct AtomicActor* actor);
    bool DECGMath_AddSubtract_postfire(struct AtomicActor* actor);
    void DECGMath_AddSubtract_wrapup(struct AtomicActor* actor);
    struct AtomicActor* DECGMath_AddSubtract_New() {
        struct AtomicActor* DECGMath_AddSubtract = AtomicActor_New();
        #ifdef _debugging
        ((struct AtomicActor*)DECGMath_AddSubtract)->setName((struct AtomicActor *)DECGMath_AddSubtract, "AddSubtract");
        #endif
        DECGMath_AddSubtract->container = DECGMath;
        DECGMath_AddSubtract->preinitialize = DECGMath_AddSubtract_preinitialize;
        DECGMath_AddSubtract->initialize = DECGMath_AddSubtract_initialize;
        DECGMath_AddSubtract->prefire = DECGMath_AddSubtract_prefire;
        DECGMath_AddSubtract->fire = DECGMath_AddSubtract_fire;
        DECGMath_AddSubtract->postfire = DECGMath_AddSubtract_postfire;
        DECGMath_AddSubtract->wrapup = DECGMath_AddSubtract_wrapup;
        plus = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        plus->setName((struct IOPort*)plus, "plus");
        #endif
        plus->container = (struct Actor*)DECGMath_AddSubtract;
        plus->_isInsideConnected = false;
        plus->_isOutsideConnected = true;
        plus->_isInput = true;
        plus->_isOutput = false;
        plus->_isMultiport = true;
        plus->_width = 2;
        plus->_insideWidth = 0;
        plus->_numberOfSinks = 2;
        plus->_numberOfSources = 2;
        plus->_type = TYPE_Int;
        pblListAdd(DECGMath_AddSubtract->_inputPorts, plus);
        PblList* plus_0 = pblListNewArrayList();
        struct DEReceiver* plus_0_0 = DEReceiver_New();
        plus_0_0->container = (struct IOPort*)plus;
        plus_0_0->_director = (struct DEDirector*)(*(DECGMath_AddSubtract->getDirector))(DECGMath_AddSubtract);
        pblListAdd(plus_0, plus_0_0);
        pblListAdd(plus->_localReceivers , plus_0);
        PblList* plus_1 = pblListNewArrayList();
        struct DEReceiver* plus_1_0 = DEReceiver_New();
        plus_1_0->container = (struct IOPort*)plus;
        plus_1_0->_director = (struct DEDirector*)(*(DECGMath_AddSubtract->getDirector))(DECGMath_AddSubtract);
        pblListAdd(plus_1, plus_1_0);
        pblListAdd(plus->_localReceivers , plus_1);
        output = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        output->setName((struct IOPort*)output, "output");
        #endif
        output->container = (struct Actor*)DECGMath_AddSubtract;
        output->_isInsideConnected = false;
        output->_isOutsideConnected = true;
        output->_isInput = false;
        output->_isOutput = true;
        output->_isMultiport = false;
        output->_width = 1;
        output->_insideWidth = 0;
        output->_numberOfSinks = 1;
        output->_numberOfSources = 0;
        output->_type = TYPE_Int;
        pblListAdd(DECGMath_AddSubtract->_outputPorts, output);
        PblList* output__0 = pblListNewArrayList();
        pblListAdd(output->_farReceivers, output__0);
        return DECGMath_AddSubtract;
    }
    struct IOPort* DECGMath_AddSubtract_get_plus() {
        return (struct IOPort*) plus;
    }
    struct IOPort* DECGMath_AddSubtract_get_output() {
        return (struct IOPort*) output;
    }
    void DECGMath_AddSubtract_preinitialize(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Preinitalization of the actor : DECGMath_AddSubtract */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the preinitalization of the actor : DECGMath_AddSubtract */
    void DECGMath_AddSubtract_initialize(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Initalization of the actor : DECGMath_AddSubtract */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the initalization of the actor : DECGMath_AddSubtract */
    bool DECGMath_AddSubtract_prefire(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        prefire of the actor : DECGMath_AddSubtract */
        return true;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the prefire of the actor : DECGMath_AddSubtract */
    #ifdef __cplusplus
}
#endif
void DECGMath_AddSubtract_fire(struct AtomicActor* actor) {
    DECGMath_AddSubtract__result = 0;
    bool triggered = false;
    if ((*(plus->hasToken))((struct IOPort*) plus, 0)) {
        triggered = true;
        DECGMath_AddSubtract__result = add_Int_Int(DECGMath_AddSubtract__result, (*(plus->get))((struct IOPort*) plus, 0)->payload.Int);
    }
    if ((*(plus->hasToken))((struct IOPort*) plus, 1)) {
        triggered = true;
        DECGMath_AddSubtract__result = add_Int_Int(DECGMath_AddSubtract__result, (*(plus->get))((struct IOPort*) plus, 1)->payload.Int);
    }
    if (triggered) {
        (*(output->send))((struct IOPort*) output, 0, Int_new(DECGMath_AddSubtract__result));
    }
}
#ifdef __cplusplus
extern "C" {
    #endif
    bool DECGMath_AddSubtract_postfire(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Postfire of the actor : DECGMath_AddSubtract */
        return true;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the postfire of the actor : DECGMath_AddSubtract */
    void DECGMath_AddSubtract_wrapup(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Wrapup of the actor : DECGMath_AddSubtract */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the wrapup of the actor : DECGMath_AddSubtract */
    #ifdef __cplusplus
}
#endif
