/* ptolemy.cg.kernel.generic.GenericCodeGenerator
Generated by Ptolemy II (http://ptolemy.eecs.berkeley.edu)
Copyright (c) 2005-2016 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.
IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS.
*/
#ifdef __cplusplus
extern "C" {
    #endif
    #include "DECGMath_Ramp.h"
    #ifdef __cplusplus
}
#endif
/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
Variable declaration code */
/* ptolemy.cg.kernel.generic.program.ProgramCodeGeneratorAdapter
preinitRamp */
int DECGMath_Ramp__state;
/* ptolemy.cg.adapter.generic.program.procedural.c.adapters.ptolemy.domains.de.kernel.DEDirector
DECGMath_DE_Director's referenced parameter declarations. */
int DECGMath_Ramp_step_;
/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
end variable declaration code */
#ifdef __cplusplus
extern "C" {
    #endif
    static struct TypedIOPort* trigger;
    static struct TypedIOPort* output;
    void DECGMath_Ramp_preinitialize(struct AtomicActor* actor);
    void DECGMath_Ramp_initialize(struct AtomicActor* actor);
    bool DECGMath_Ramp_prefire(struct AtomicActor* actor);
    void DECGMath_Ramp_fire(struct AtomicActor* actor);
    bool DECGMath_Ramp_postfire(struct AtomicActor* actor);
    void DECGMath_Ramp_wrapup(struct AtomicActor* actor);
    struct AtomicActor* DECGMath_Ramp_New() {
        struct AtomicActor* DECGMath_Ramp = AtomicActor_New();
        #ifdef _debugging
        ((struct AtomicActor*)DECGMath_Ramp)->setName((struct AtomicActor *)DECGMath_Ramp, "Ramp");
        #endif
        DECGMath_Ramp->container = DECGMath;
        DECGMath_Ramp->preinitialize = DECGMath_Ramp_preinitialize;
        DECGMath_Ramp->initialize = DECGMath_Ramp_initialize;
        DECGMath_Ramp->prefire = DECGMath_Ramp_prefire;
        DECGMath_Ramp->fire = DECGMath_Ramp_fire;
        DECGMath_Ramp->postfire = DECGMath_Ramp_postfire;
        DECGMath_Ramp->wrapup = DECGMath_Ramp_wrapup;
        trigger = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        trigger->setName((struct IOPort*)trigger, "trigger");
        #endif
        trigger->container = (struct Actor*)DECGMath_Ramp;
        trigger->_isInsideConnected = false;
        trigger->_isOutsideConnected = true;
        trigger->_isInput = true;
        trigger->_isOutput = false;
        trigger->_isMultiport = true;
        trigger->_width = 1;
        trigger->_insideWidth = 0;
        trigger->_numberOfSinks = 0;
        trigger->_numberOfSources = 1;
        trigger->_type = TYPE_Int;
        pblListAdd(DECGMath_Ramp->_inputPorts, trigger);
        PblList* trigger_0 = pblListNewArrayList();
        struct DEReceiver* trigger_0_0 = DEReceiver_New();
        trigger_0_0->container = (struct IOPort*)trigger;
        trigger_0_0->_director = (struct DEDirector*)(*(DECGMath_Ramp->getDirector))(DECGMath_Ramp);
        pblListAdd(trigger_0, trigger_0_0);
        pblListAdd(trigger->_localReceivers , trigger_0);
        output = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        output->setName((struct IOPort*)output, "output");
        #endif
        output->container = (struct Actor*)DECGMath_Ramp;
        output->_isInsideConnected = false;
        output->_isOutsideConnected = true;
        output->_isInput = false;
        output->_isOutput = true;
        output->_isMultiport = false;
        output->_width = 1;
        output->_insideWidth = 0;
        output->_numberOfSinks = 3;
        output->_numberOfSources = 0;
        output->_type = TYPE_Int;
        pblListAdd(DECGMath_Ramp->_outputPorts, output);
        PblList* output__0 = pblListNewArrayList();
        pblListAdd(output->_farReceivers, output__0);
        return DECGMath_Ramp;
    }
    struct IOPort* DECGMath_Ramp_get_trigger() {
        return (struct IOPort*) trigger;
    }
    struct IOPort* DECGMath_Ramp_get_output() {
        return (struct IOPort*) output;
    }
    void DECGMath_Ramp_preinitialize(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Preinitalization of the actor : DECGMath_Ramp */
        /* ptolemy.cg.adapter.generic.program.procedural.c.adapters.ptolemy.domains.de.kernel.DEDirector
        Ramp's parameter initialization */
        DECGMath_Ramp_step_ = 1;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the preinitalization of the actor : DECGMath_Ramp */
    void DECGMath_Ramp_initialize(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Initalization of the actor : DECGMath_Ramp */
        /* ptolemy.cg.adapter.generic.program.procedural.adapters.ptolemy.actor.lib.Ramp
        initialize Ramp */
        DECGMath_Ramp__state = 0;
        DECGMath_Ramp_step_ = 1;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the initalization of the actor : DECGMath_Ramp */
    bool DECGMath_Ramp_prefire(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        prefire of the actor : DECGMath_Ramp */
        return true;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the prefire of the actor : DECGMath_Ramp */
    #ifdef __cplusplus
}
#endif
void DECGMath_Ramp_fire(struct AtomicActor* actor) {
    (*(output->send))((struct IOPort*) output, 0, Int_new(DECGMath_Ramp__state));
    if (false) {
        DECGMath_Ramp_step_ = Int_new(0)->payload.Int;
    }
    DECGMath_Ramp__state += (int)DECGMath_Ramp_step_;
}
#ifdef __cplusplus
extern "C" {
    #endif
    bool DECGMath_Ramp_postfire(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Postfire of the actor : DECGMath_Ramp */
        return true;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the postfire of the actor : DECGMath_Ramp */
    void DECGMath_Ramp_wrapup(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Wrapup of the actor : DECGMath_Ramp */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the wrapup of the actor : DECGMath_Ramp */
    #ifdef __cplusplus
}
#endif
