/* Generated by Ptolemy II (http://ptolemy.eecs.berkeley.edu)
Copyright (c) 2005-2016 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.
IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS.
*/
#ifdef __cplusplus
extern "C" {
    #endif
    #include "DECGHeterogeneousMk2_ModalModel_state_Scale.h"
    #ifdef __cplusplus
}
#endif
/* Variable declaration code */
/* end variable declaration code */
#ifdef __cplusplus
extern "C" {
    #endif
    static struct TypedIOPort* input;
    static struct TypedIOPort* output;
    void DECGHeterogeneousMk2_ModalModel_state_Scale_preinitialize(struct AtomicActor* actor);
    void DECGHeterogeneousMk2_ModalModel_state_Scale_initialize(struct AtomicActor* actor);
    bool DECGHeterogeneousMk2_ModalModel_state_Scale_prefire(struct AtomicActor* actor);
    void DECGHeterogeneousMk2_ModalModel_state_Scale_fire(struct AtomicActor* actor);
    bool DECGHeterogeneousMk2_ModalModel_state_Scale_postfire(struct AtomicActor* actor);
    void DECGHeterogeneousMk2_ModalModel_state_Scale_wrapup(struct AtomicActor* actor);
    struct AtomicActor* DECGHeterogeneousMk2_ModalModel_state_Scale_New() {
        struct AtomicActor* DECGHeterogeneousMk2_ModalModel_state_Scale = AtomicActor_New();
        #ifdef _debugging
        ((struct AtomicActor*)DECGHeterogeneousMk2_ModalModel_state_Scale)->setName((struct AtomicActor *)DECGHeterogeneousMk2_ModalModel_state_Scale, "Scale");
        #endif
        DECGHeterogeneousMk2_ModalModel_state_Scale->container = DECGHeterogeneousMk2_ModalModel_state;
        DECGHeterogeneousMk2_ModalModel_state_Scale->preinitialize = DECGHeterogeneousMk2_ModalModel_state_Scale_preinitialize;
        DECGHeterogeneousMk2_ModalModel_state_Scale->initialize = DECGHeterogeneousMk2_ModalModel_state_Scale_initialize;
        DECGHeterogeneousMk2_ModalModel_state_Scale->prefire = DECGHeterogeneousMk2_ModalModel_state_Scale_prefire;
        DECGHeterogeneousMk2_ModalModel_state_Scale->fire = DECGHeterogeneousMk2_ModalModel_state_Scale_fire;
        DECGHeterogeneousMk2_ModalModel_state_Scale->postfire = DECGHeterogeneousMk2_ModalModel_state_Scale_postfire;
        DECGHeterogeneousMk2_ModalModel_state_Scale->wrapup = DECGHeterogeneousMk2_ModalModel_state_Scale_wrapup;
        input = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        input->setName((struct IOPort*)input, "input");
        #endif
        input->container = (struct Actor*)DECGHeterogeneousMk2_ModalModel_state_Scale;
        input->_isInsideConnected = false;
        input->_isOutsideConnected = true;
        input->_isInput = true;
        input->_isOutput = false;
        input->_isMultiport = false;
        input->_width = 1;
        input->_insideWidth = 0;
        input->_numberOfSinks = 0;
        input->_numberOfSources = 1;
        input->_type = TYPE_Int;
        pblListAdd(DECGHeterogeneousMk2_ModalModel_state_Scale->_inputPorts, input);
        PblList* input_0 = pblListNewArrayList();
        struct SDFReceiver* input_0_0 = SDFReceiver_New();
        input_0_0->container = (struct IOPort*)input;
        pblListAdd(input_0, input_0_0);
        pblListAdd(input->_localReceivers , input_0);
        output = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        output->setName((struct IOPort*)output, "output");
        #endif
        output->container = (struct Actor*)DECGHeterogeneousMk2_ModalModel_state_Scale;
        output->_isInsideConnected = false;
        output->_isOutsideConnected = true;
        output->_isInput = false;
        output->_isOutput = true;
        output->_isMultiport = false;
        output->_width = 1;
        output->_insideWidth = 0;
        output->_numberOfSinks = 1;
        output->_numberOfSources = 0;
        output->_type = TYPE_Int;
        pblListAdd(DECGHeterogeneousMk2_ModalModel_state_Scale->_outputPorts, output);
        PblList* output__0 = pblListNewArrayList();
        pblListAdd(output->_farReceivers, output__0);
        return DECGHeterogeneousMk2_ModalModel_state_Scale;
    }
    struct IOPort* DECGHeterogeneousMk2_ModalModel_state_Scale_get_input() {
        return (struct IOPort*) input;
    }
    struct IOPort* DECGHeterogeneousMk2_ModalModel_state_Scale_get_output() {
        return (struct IOPort*) output;
    }
    void DECGHeterogeneousMk2_ModalModel_state_Scale_preinitialize(struct AtomicActor* actor) {
        /* Preinitalization of the actor : DECGHeterogeneousMk2_ModalModel_state_Scale */
    }/* End of the preinitalization of the actor : DECGHeterogeneousMk2_ModalModel_state_Scale */
    void DECGHeterogeneousMk2_ModalModel_state_Scale_initialize(struct AtomicActor* actor) {
        /* Initalization of the actor : DECGHeterogeneousMk2_ModalModel_state_Scale */
    }/* End of the initalization of the actor : DECGHeterogeneousMk2_ModalModel_state_Scale */
    bool DECGHeterogeneousMk2_ModalModel_state_Scale_prefire(struct AtomicActor* actor) {
        /* prefire of the actor : DECGHeterogeneousMk2_ModalModel_state_Scale */
        return true;
    }/* End of the prefire of the actor : DECGHeterogeneousMk2_ModalModel_state_Scale */
    #ifdef __cplusplus
}
#endif
void DECGHeterogeneousMk2_ModalModel_state_Scale_fire(struct AtomicActor* actor) {
    // primitive is commutative.
    (*(output->send))((struct IOPort*) output, 0, Int_new(1 * (*(input->get))((struct IOPort*) input, 0)->payload.Int));
}
#ifdef __cplusplus
extern "C" {
    #endif
    bool DECGHeterogeneousMk2_ModalModel_state_Scale_postfire(struct AtomicActor* actor) {
        /* Postfire of the actor : DECGHeterogeneousMk2_ModalModel_state_Scale */
        return true;
    }/* End of the postfire of the actor : DECGHeterogeneousMk2_ModalModel_state_Scale */
    void DECGHeterogeneousMk2_ModalModel_state_Scale_wrapup(struct AtomicActor* actor) {
        /* Wrapup of the actor : DECGHeterogeneousMk2_ModalModel_state_Scale */
    }/* End of the wrapup of the actor : DECGHeterogeneousMk2_ModalModel_state_Scale */
    #ifdef __cplusplus
}
#endif
