/* Generated by Ptolemy II (http://ptolemy.eecs.berkeley.edu)
Copyright (c) 2005-2016 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.
IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS.
*/
#ifdef __cplusplus
extern "C" {
    #endif
    #include "ScaleCFlat_Ramp.h"
    #ifdef __cplusplus
}
#endif
/* Variable declaration code */
/* preinitRamp */
int ScaleCFlat_Ramp__state;
/* ScaleCFlat_SDF_Director's referenced parameter declarations. */
int ScaleCFlat_Ramp_step_;
/* end variable declaration code */
#ifdef __cplusplus
extern "C" {
    #endif
    static struct TypedIOPort* output;
    void ScaleCFlat_Ramp_preinitialize(struct AtomicActor* actor);
    void ScaleCFlat_Ramp_initialize(struct AtomicActor* actor);
    bool ScaleCFlat_Ramp_prefire(struct AtomicActor* actor);
    void ScaleCFlat_Ramp_fire(struct AtomicActor* actor);
    bool ScaleCFlat_Ramp_postfire(struct AtomicActor* actor);
    void ScaleCFlat_Ramp_wrapup(struct AtomicActor* actor);
    struct AtomicActor* ScaleCFlat_Ramp_New() {
        struct AtomicActor* ScaleCFlat_Ramp = AtomicActor_New();
        #ifdef _debugging
        ((struct AtomicActor*)ScaleCFlat_Ramp)->setName((struct AtomicActor *)ScaleCFlat_Ramp, "Ramp");
        #endif
        ScaleCFlat_Ramp->container = ScaleCFlat;
        ScaleCFlat_Ramp->preinitialize = ScaleCFlat_Ramp_preinitialize;
        ScaleCFlat_Ramp->initialize = ScaleCFlat_Ramp_initialize;
        ScaleCFlat_Ramp->prefire = ScaleCFlat_Ramp_prefire;
        ScaleCFlat_Ramp->fire = ScaleCFlat_Ramp_fire;
        ScaleCFlat_Ramp->postfire = ScaleCFlat_Ramp_postfire;
        ScaleCFlat_Ramp->wrapup = ScaleCFlat_Ramp_wrapup;
        output = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        output->setName((struct IOPort*)output, "output");
        #endif
        output->container = (struct Actor*)ScaleCFlat_Ramp;
        output->_isInsideConnected = false;
        output->_isOutsideConnected = true;
        output->_isInput = false;
        output->_isOutput = true;
        output->_isMultiport = false;
        output->_width = 1;
        output->_insideWidth = 0;
        output->_numberOfSinks = 1;
        output->_numberOfSources = 0;
        output->_type = TYPE_Int;
        pblListAdd(ScaleCFlat_Ramp->_outputPorts, output);
        PblList* output__0 = pblListNewArrayList();
        pblListAdd(output->_farReceivers, output__0);
        return ScaleCFlat_Ramp;
    }
    struct IOPort* ScaleCFlat_Ramp_get_output() {
        return (struct IOPort*) output;
    }
    void ScaleCFlat_Ramp_preinitialize(struct AtomicActor* actor) {
        /* Preinitalization of the actor : ScaleCFlat_Ramp */
        /* Ramp's parameter initialization */
        ScaleCFlat_Ramp_step_ = 1;
    }/* End of the preinitalization of the actor : ScaleCFlat_Ramp */
    void ScaleCFlat_Ramp_initialize(struct AtomicActor* actor) {
        /* Initalization of the actor : ScaleCFlat_Ramp */
        /* initialize Ramp */
        ScaleCFlat_Ramp__state = 0;
        ScaleCFlat_Ramp_step_ = 1;
    }/* End of the initalization of the actor : ScaleCFlat_Ramp */
    bool ScaleCFlat_Ramp_prefire(struct AtomicActor* actor) {
        /* prefire of the actor : ScaleCFlat_Ramp */
        return true;
    }/* End of the prefire of the actor : ScaleCFlat_Ramp */
    #ifdef __cplusplus
}
#endif
void ScaleCFlat_Ramp_fire(struct AtomicActor* actor) {
    (*(output->send))((struct IOPort*) output, 0, Int_new(ScaleCFlat_Ramp__state));
    if (false) {
        ScaleCFlat_Ramp_step_ = Int_new(0)->payload.Int;
    }
    ScaleCFlat_Ramp__state += (int)ScaleCFlat_Ramp_step_;
}
#ifdef __cplusplus
extern "C" {
    #endif
    bool ScaleCFlat_Ramp_postfire(struct AtomicActor* actor) {
        /* Postfire of the actor : ScaleCFlat_Ramp */
        return true;
    }/* End of the postfire of the actor : ScaleCFlat_Ramp */
    void ScaleCFlat_Ramp_wrapup(struct AtomicActor* actor) {
        /* Wrapup of the actor : ScaleCFlat_Ramp */
    }/* End of the wrapup of the actor : ScaleCFlat_Ramp */
    #ifdef __cplusplus
}
#endif
