/* Generated by Ptolemy II (http://ptolemy.eecs.berkeley.edu)
Copyright (c) 2005-2016 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.
IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS.
*/
#ifndef _SCALECFLAT_H_
#define _SCALECFLAT_H_
#include "_CompositeActor.h"
#include "_AtomicActor.h"
#include "_SDFDirector.h"
#include "ScaleCFlat_Ramp.h"
#include "ScaleCFlat_Display.h"
#include "ScaleCFlat_Scale.h"
#ifdef __cplusplus
extern "C" {
    #endif
    extern struct CompositeActor* ScaleCFlat;
    extern struct CompositeActor* ScaleCFlat_New();
    void ScaleCFlat_Schedule_iterate();
    extern struct AtomicActor* ScaleCFlat_Ramp;
    extern struct AtomicActor* ScaleCFlat_Display;
    extern struct AtomicActor* ScaleCFlat_Scale;
    #ifdef __cplusplus
}
#endif
#endif /* SCALECFLAT */
