/* ptolemy.cg.kernel.generic.GenericCodeGenerator
Generated by Ptolemy II (http://ptolemy.eecs.berkeley.edu)
Copyright (c) 2005-2016 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.
IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS.
*/
#ifdef __cplusplus
extern "C" {
    #endif
    #include "DECGPiSquare_MultiplyDivide.h"
    #ifdef __cplusplus
}
#endif
/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
Variable declaration code */
/* ptolemy.cg.adapter.generic.program.procedural.adapters.ptolemy.actor.lib.MultiplyDivide
preinitialize MultiplyDivide */
double DECGPiSquare_MultiplyDivide__result;
/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
end variable declaration code */
#ifdef __cplusplus
extern "C" {
    #endif
    static struct TypedIOPort* multiply;
    static struct TypedIOPort* divide;
    static struct TypedIOPort* output;
    void DECGPiSquare_MultiplyDivide_preinitialize(struct AtomicActor* actor);
    void DECGPiSquare_MultiplyDivide_initialize(struct AtomicActor* actor);
    bool DECGPiSquare_MultiplyDivide_prefire(struct AtomicActor* actor);
    void DECGPiSquare_MultiplyDivide_fire(struct AtomicActor* actor);
    bool DECGPiSquare_MultiplyDivide_postfire(struct AtomicActor* actor);
    void DECGPiSquare_MultiplyDivide_wrapup(struct AtomicActor* actor);
    struct AtomicActor* DECGPiSquare_MultiplyDivide_New() {
        struct AtomicActor* DECGPiSquare_MultiplyDivide = AtomicActor_New();
        #ifdef _debugging
        ((struct AtomicActor*)DECGPiSquare_MultiplyDivide)->setName((struct AtomicActor *)DECGPiSquare_MultiplyDivide, "MultiplyDivide");
        #endif
        DECGPiSquare_MultiplyDivide->container = DECGPiSquare;
        DECGPiSquare_MultiplyDivide->preinitialize = DECGPiSquare_MultiplyDivide_preinitialize;
        DECGPiSquare_MultiplyDivide->initialize = DECGPiSquare_MultiplyDivide_initialize;
        DECGPiSquare_MultiplyDivide->prefire = DECGPiSquare_MultiplyDivide_prefire;
        DECGPiSquare_MultiplyDivide->fire = DECGPiSquare_MultiplyDivide_fire;
        DECGPiSquare_MultiplyDivide->postfire = DECGPiSquare_MultiplyDivide_postfire;
        DECGPiSquare_MultiplyDivide->wrapup = DECGPiSquare_MultiplyDivide_wrapup;
        multiply = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        multiply->setName((struct IOPort*)multiply, "multiply");
        #endif
        multiply->container = (struct Actor*)DECGPiSquare_MultiplyDivide;
        multiply->_isInsideConnected = false;
        multiply->_isOutsideConnected = true;
        multiply->_isInput = true;
        multiply->_isOutput = false;
        multiply->_isMultiport = true;
        multiply->_width = 1;
        multiply->_insideWidth = 0;
        multiply->_numberOfSinks = 0;
        multiply->_numberOfSources = 1;
        multiply->_type = TYPE_Double;
        pblListAdd(DECGPiSquare_MultiplyDivide->_inputPorts, multiply);
        PblList* multiply_0 = pblListNewArrayList();
        struct DEReceiver* multiply_0_0 = DEReceiver_New();
        multiply_0_0->container = (struct IOPort*)multiply;
        multiply_0_0->_director = (struct DEDirector*)(*(DECGPiSquare_MultiplyDivide->getDirector))(DECGPiSquare_MultiplyDivide);
        pblListAdd(multiply_0, multiply_0_0);
        pblListAdd(multiply->_localReceivers , multiply_0);
        divide = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        divide->setName((struct IOPort*)divide, "divide");
        #endif
        divide->container = (struct Actor*)DECGPiSquare_MultiplyDivide;
        divide->_isInsideConnected = false;
        divide->_isOutsideConnected = true;
        divide->_isInput = true;
        divide->_isOutput = false;
        divide->_isMultiport = true;
        divide->_width = 2;
        divide->_insideWidth = 0;
        divide->_numberOfSinks = 0;
        divide->_numberOfSources = 2;
        divide->_type = TYPE_Int;
        pblListAdd(DECGPiSquare_MultiplyDivide->_inputPorts, divide);
        PblList* divide_0 = pblListNewArrayList();
        struct DEReceiver* divide_0_0 = DEReceiver_New();
        divide_0_0->container = (struct IOPort*)divide;
        divide_0_0->_director = (struct DEDirector*)(*(DECGPiSquare_MultiplyDivide->getDirector))(DECGPiSquare_MultiplyDivide);
        pblListAdd(divide_0, divide_0_0);
        pblListAdd(divide->_localReceivers , divide_0);
        PblList* divide_1 = pblListNewArrayList();
        struct DEReceiver* divide_1_0 = DEReceiver_New();
        divide_1_0->container = (struct IOPort*)divide;
        divide_1_0->_director = (struct DEDirector*)(*(DECGPiSquare_MultiplyDivide->getDirector))(DECGPiSquare_MultiplyDivide);
        pblListAdd(divide_1, divide_1_0);
        pblListAdd(divide->_localReceivers , divide_1);
        output = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        output->setName((struct IOPort*)output, "output");
        #endif
        output->container = (struct Actor*)DECGPiSquare_MultiplyDivide;
        output->_isInsideConnected = false;
        output->_isOutsideConnected = true;
        output->_isInput = false;
        output->_isOutput = true;
        output->_isMultiport = false;
        output->_width = 1;
        output->_insideWidth = 0;
        output->_numberOfSinks = 1;
        output->_numberOfSources = 0;
        output->_type = TYPE_Double;
        pblListAdd(DECGPiSquare_MultiplyDivide->_outputPorts, output);
        PblList* output__0 = pblListNewArrayList();
        pblListAdd(output->_farReceivers, output__0);
        return DECGPiSquare_MultiplyDivide;
    }
    struct IOPort* DECGPiSquare_MultiplyDivide_get_multiply() {
        return (struct IOPort*) multiply;
    }
    struct IOPort* DECGPiSquare_MultiplyDivide_get_divide() {
        return (struct IOPort*) divide;
    }
    struct IOPort* DECGPiSquare_MultiplyDivide_get_output() {
        return (struct IOPort*) output;
    }
    void DECGPiSquare_MultiplyDivide_preinitialize(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Preinitalization of the actor : DECGPiSquare_MultiplyDivide */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the preinitalization of the actor : DECGPiSquare_MultiplyDivide */
    void DECGPiSquare_MultiplyDivide_initialize(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Initalization of the actor : DECGPiSquare_MultiplyDivide */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the initalization of the actor : DECGPiSquare_MultiplyDivide */
    bool DECGPiSquare_MultiplyDivide_prefire(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        prefire of the actor : DECGPiSquare_MultiplyDivide */
        return true;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the prefire of the actor : DECGPiSquare_MultiplyDivide */
    #ifdef __cplusplus
}
#endif
void DECGPiSquare_MultiplyDivide_fire(struct AtomicActor* actor) {
    if ((*(multiply->hasToken))((struct IOPort*) multiply, 0)) {
        DECGPiSquare_MultiplyDivide__result = convert_Double_Double((*(multiply->get))((struct IOPort*) multiply, 0)->payload.Double);
    }
    else {
        DECGPiSquare_MultiplyDivide__result = convert_Int_Double(1);
    }
    if ((*(divide->hasToken))((struct IOPort*) divide, 0)) {
        DECGPiSquare_MultiplyDivide__result = divide_Double_Int(DECGPiSquare_MultiplyDivide__result, (*(divide->get))((struct IOPort*) divide, 0)->payload.Int);
    }
    if ((*(divide->hasToken))((struct IOPort*) divide, 1)) {
        DECGPiSquare_MultiplyDivide__result = divide_Double_Int(DECGPiSquare_MultiplyDivide__result, (*(divide->get))((struct IOPort*) divide, 1)->payload.Int);
    }
    (*(output->send))((struct IOPort*) output, 0, Double_new(DECGPiSquare_MultiplyDivide__result));
}
#ifdef __cplusplus
extern "C" {
    #endif
    bool DECGPiSquare_MultiplyDivide_postfire(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Postfire of the actor : DECGPiSquare_MultiplyDivide */
        return true;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the postfire of the actor : DECGPiSquare_MultiplyDivide */
    void DECGPiSquare_MultiplyDivide_wrapup(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Wrapup of the actor : DECGPiSquare_MultiplyDivide */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the wrapup of the actor : DECGPiSquare_MultiplyDivide */
    #ifdef __cplusplus
}
#endif
