/* ptolemy.cg.kernel.generic.GenericCodeGenerator
Generated by Ptolemy II (http://ptolemy.eecs.berkeley.edu)
Copyright (c) 2005-2016 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.
IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS.
*/
#ifdef __cplusplus
extern "C" {
    #endif
    #include "DECGPiSquare_DiscreteClock.h"
    #ifdef __cplusplus
}
#endif
/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
Variable declaration code */
/* ptolemy.cg.kernel.generic.program.ProgramCodeGeneratorAdapter
preinitDiscreteClock */
int DECGPiSquare_DiscreteClock__phase;
Time DECGPiSquare_DiscreteClock__period;
Time DECGPiSquare_DiscreteClock__cycleStartTime;
Time DECGPiSquare_DiscreteClock__stopTime;
int * DECGPiSquare_DiscreteClock__values;
Time * DECGPiSquare_DiscreteClock__offsets;
int DECGPiSquare_DiscreteClock__offsetsNumber;
boolean DECGPiSquare_DiscreteClock__enabled;
boolean DECGPiSquare_DiscreteClock__triggered;
Time DECGPiSquare_DiscreteClock__nextOutputTime;
int DECGPiSquare_DiscreteClock__nextOutputIndex;
boolean DECGPiSquare_DiscreteClock__outputProduced;
/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
end variable declaration code */
#ifdef __cplusplus
extern "C" {
    #endif
    static struct TypedIOPort* output;
    void DECGPiSquare_DiscreteClock_preinitialize(struct AtomicActor* actor);
    void DECGPiSquare_DiscreteClock_initialize(struct AtomicActor* actor);
    bool DECGPiSquare_DiscreteClock_prefire(struct AtomicActor* actor);
    void DECGPiSquare_DiscreteClock_fire(struct AtomicActor* actor);
    bool DECGPiSquare_DiscreteClock_postfire(struct AtomicActor* actor);
    void DECGPiSquare_DiscreteClock_wrapup(struct AtomicActor* actor);
    struct AtomicActor* DECGPiSquare_DiscreteClock_New() {
        struct AtomicActor* DECGPiSquare_DiscreteClock = AtomicActor_New();
        #ifdef _debugging
        ((struct AtomicActor*)DECGPiSquare_DiscreteClock)->setName((struct AtomicActor *)DECGPiSquare_DiscreteClock, "DiscreteClock");
        #endif
        DECGPiSquare_DiscreteClock->container = DECGPiSquare;
        DECGPiSquare_DiscreteClock->preinitialize = DECGPiSquare_DiscreteClock_preinitialize;
        DECGPiSquare_DiscreteClock->initialize = DECGPiSquare_DiscreteClock_initialize;
        DECGPiSquare_DiscreteClock->prefire = DECGPiSquare_DiscreteClock_prefire;
        DECGPiSquare_DiscreteClock->fire = DECGPiSquare_DiscreteClock_fire;
        DECGPiSquare_DiscreteClock->postfire = DECGPiSquare_DiscreteClock_postfire;
        DECGPiSquare_DiscreteClock->wrapup = DECGPiSquare_DiscreteClock_wrapup;
        output = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        output->setName((struct IOPort*)output, "output");
        #endif
        output->container = (struct Actor*)DECGPiSquare_DiscreteClock;
        output->_isInsideConnected = false;
        output->_isOutsideConnected = true;
        output->_isInput = false;
        output->_isOutput = true;
        output->_isMultiport = false;
        output->_width = 1;
        output->_insideWidth = 0;
        output->_numberOfSinks = 2;
        output->_numberOfSources = 0;
        output->_type = TYPE_Int;
        pblListAdd(DECGPiSquare_DiscreteClock->_outputPorts, output);
        PblList* output__0 = pblListNewArrayList();
        pblListAdd(output->_farReceivers, output__0);
        return DECGPiSquare_DiscreteClock;
    }
    struct IOPort* DECGPiSquare_DiscreteClock_get_output() {
        return (struct IOPort*) output;
    }
    void DECGPiSquare_DiscreteClock_preinitialize(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Preinitalization of the actor : DECGPiSquare_DiscreteClock */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the preinitalization of the actor : DECGPiSquare_DiscreteClock */
    void DECGPiSquare_DiscreteClock_initialize(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Initalization of the actor : DECGPiSquare_DiscreteClock */
        DECGPiSquare_DiscreteClock__offsetsNumber = 1;
        DECGPiSquare_DiscreteClock__offsets = calloc(1, sizeof(Time));
        DECGPiSquare_DiscreteClock__offsets[0] = 0.0;
        DECGPiSquare_DiscreteClock__values = calloc(1, sizeof(TYPE_Int));
        DECGPiSquare_DiscreteClock__values[0] = 1;
        DECGPiSquare_DiscreteClock__period = 0.1;
        DECGPiSquare_DiscreteClock__phase = 0;
        DECGPiSquare_DiscreteClock__enabled = true;
        DECGPiSquare_DiscreteClock__triggered = true;
        DECGPiSquare_DiscreteClock__outputProduced = false;
        DECGPiSquare_DiscreteClock__stopTime = 100.0;
        struct Director* director = (*(actor->getDirector))(actor);
        DECGPiSquare_DiscreteClock__cycleStartTime = (*(director->getModelTime))(director);
        DECGPiSquare_DiscreteClock__nextOutputTime = DECGPiSquare_DiscreteClock__cycleStartTime + DECGPiSquare_DiscreteClock__offsets[DECGPiSquare_DiscreteClock__phase];
        DECGPiSquare_DiscreteClock__nextOutputIndex = 1;
        (*(director->fireAt))(director, (struct Actor*)actor, DECGPiSquare_DiscreteClock__nextOutputTime, DECGPiSquare_DiscreteClock__nextOutputIndex);
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the initalization of the actor : DECGPiSquare_DiscreteClock */
    bool DECGPiSquare_DiscreteClock_prefire(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        prefire of the actor : DECGPiSquare_DiscreteClock */
        return true;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the prefire of the actor : DECGPiSquare_DiscreteClock */
    #ifdef __cplusplus
}
#endif
void DECGPiSquare_DiscreteClock_fire(struct AtomicActor* actor) {
    if (!DECGPiSquare_DiscreteClock__enabled) {
        // if the clock is disabled
        return;
    }
    struct Director* director = (*(actor->getDirector))(actor);
    double comparison = DECGPiSquare_DiscreteClock__nextOutputTime - (*(director->getModelTime))(director);
    if (comparison > 0) {
        return;
    } else if (comparison == 0) {
        // It is the right time to produce an output. Check
        // the index.
        if (DECGPiSquare_DiscreteClock__nextOutputIndex > (*(((struct DEDirector*)director)->getMicrostep))((struct DEDirector*)director)) {
            // We have not yet reached the requisite index.
            // Request another firing at the current time.
            (*(director->fireAt))(director, (struct Actor*)actor, (*(director->getModelTime))(director),
            (*(((struct DEDirector*)director)->getMicrostep))((struct DEDirector*)director) + 1);
            return;
        }
        // At this point, the time matches the next output, and
        // the index either matches or exceeds the index for the next output,
        // or the director does not support superdense time.
        if (!DECGPiSquare_DiscreteClock__triggered) {
            // Pretend we produced an output so that postfire() will
            // skip to the next phase.
            DECGPiSquare_DiscreteClock__outputProduced = true;
            return;
        }
        // Ready to fire.
        if (DECGPiSquare_DiscreteClock__enabled) {
            (*(output->send))((struct IOPort*) output, 0, Int_new(DECGPiSquare_DiscreteClock__values[DECGPiSquare_DiscreteClock__phase]));
            DECGPiSquare_DiscreteClock__outputProduced = true;
        }
        return;
    }
}
#ifdef __cplusplus
extern "C" {
    #endif
    bool DECGPiSquare_DiscreteClock_postfire(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Postfire of the actor : DECGPiSquare_DiscreteClock */
        struct Director* director = (*(actor->getDirector))(actor);
        if ((*(director->getModelTime))(director) > DECGPiSquare_DiscreteClock__stopTime) {
            return true;
        }
        if (DECGPiSquare_DiscreteClock__outputProduced) {
            DECGPiSquare_DiscreteClock__phase++;
            if (DECGPiSquare_DiscreteClock__phase >= DECGPiSquare_DiscreteClock__offsetsNumber) {
                DECGPiSquare_DiscreteClock__phase = 0;
                DECGPiSquare_DiscreteClock__cycleStartTime += DECGPiSquare_DiscreteClock__period;
            }
            if (DECGPiSquare_DiscreteClock__offsets[DECGPiSquare_DiscreteClock__phase] > DECGPiSquare_DiscreteClock__period) {
                perror("An offset of the Discrete Clock is greater than the period !");
                exit(1);
            }
            Time nextOutputTime = DECGPiSquare_DiscreteClock__cycleStartTime + DECGPiSquare_DiscreteClock__offsets[DECGPiSquare_DiscreteClock__phase];
            if (DECGPiSquare_DiscreteClock__nextOutputTime == nextOutputTime) {
                DECGPiSquare_DiscreteClock__nextOutputIndex++;
            } else {
                DECGPiSquare_DiscreteClock__nextOutputTime = nextOutputTime;
                DECGPiSquare_DiscreteClock__nextOutputIndex = 1;
            }
            (*(director->fireAt))(director, (struct Actor*)actor, DECGPiSquare_DiscreteClock__nextOutputTime,
            DECGPiSquare_DiscreteClock__nextOutputIndex);
            DECGPiSquare_DiscreteClock__outputProduced = false;
            if (false) {
                DECGPiSquare_DiscreteClock__triggered = false;
            }
        }
        return true;
        return true;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the postfire of the actor : DECGPiSquare_DiscreteClock */
    void DECGPiSquare_DiscreteClock_wrapup(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Wrapup of the actor : DECGPiSquare_DiscreteClock */
        /* ptolemy.cg.kernel.generic.program.ProgramCodeGeneratorAdapter
        wrapupDiscreteClock */
        free(DECGPiSquare_DiscreteClock__values);
        free(DECGPiSquare_DiscreteClock__offsets);
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the wrapup of the actor : DECGPiSquare_DiscreteClock */
    #ifdef __cplusplus
}
#endif
