/* Generated by Ptolemy II (http://ptolemy.eecs.berkeley.edu)
Copyright (c) 2005-2016 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.
IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS.
*/
#include "DECGHeterogeneousMk2_ModalModel.h"
/* About to define ports. */
static struct TypedIOPort* in;
static struct TypedIOPort* out;/* CCodeGenerator:_generateAndWriteCompositeActorCode() */
struct CompositeActor* DECGHeterogeneousMk2_ModalModel;
static struct TypedIOPort* in;
static struct TypedIOPort* out;
struct CompositeActor* DECGHeterogeneousMk2_ModalModel_New() {
    DECGHeterogeneousMk2_ModalModel = CompositeActor_New();
    #ifdef _debugging
    ((struct CompositeActor*)DECGHeterogeneousMk2_ModalModel)->setName((struct CompositeActor *)DECGHeterogeneousMk2_ModalModel, "ModalModel");
    #endif
    DECGHeterogeneousMk2_ModalModel->container = DECGHeterogeneousMk2;
    /* Creation of the director */
    struct FSMDirector* DECGHeterogeneousMk2_ModalModel__Director = FSMDirector_New();
    #ifdef _debugging
    ((struct Director*)DECGHeterogeneousMk2_ModalModel__Director)->setName((struct Director *)DECGHeterogeneousMk2_ModalModel__Director, "_Director");
    #endif
    DECGHeterogeneousMk2_ModalModel->_director = (struct Director*)DECGHeterogeneousMk2_ModalModel__Director;
    /* Actor Initializations */
    DECGHeterogeneousMk2_ModalModel_state = DECGHeterogeneousMk2_ModalModel_state_New();
    pblListAdd(DECGHeterogeneousMk2_ModalModel->_containedEntities, DECGHeterogeneousMk2_ModalModel_state);
    DECGHeterogeneousMk2_ModalModel_state2 = DECGHeterogeneousMk2_ModalModel_state2_New();
    pblListAdd(DECGHeterogeneousMk2_ModalModel->_containedEntities, DECGHeterogeneousMk2_ModalModel_state2);
    /* Creation of the ports of the container. */
    in = (struct TypedIOPort*)TypedIOPort_New();
    #ifdef _debugging
    in->setName((struct IOPort*)in, "in");
    #endif
    in->container = (struct Actor*)DECGHeterogeneousMk2_ModalModel;
    in->_isInsideConnected = true;
    in->_isOutsideConnected = true;
    in->_isInput = true;
    in->_isOutput = false;
    in->_isMultiport = false;
    in->_width = 1;
    in->_insideWidth = 1;
    in->_numberOfSinks = 0;
    in->_numberOfSources = 1;
    in->_type = TYPE_Int;
    pblListAdd(DECGHeterogeneousMk2_ModalModel->_inputPorts, in);
    PblList* in_0 = pblListNewArrayList();
    struct DEReceiver* in_0_0 = DEReceiver_New();
    in_0_0->container = (struct IOPort*)in;
    in_0_0->_director = (struct DEDirector*)(*(DECGHeterogeneousMk2_ModalModel->getExecutiveDirector))(DECGHeterogeneousMk2_ModalModel);
    pblListAdd(in_0, in_0_0);
    pblListAdd(in->_localReceivers , in_0);
    PblList* in__0 = pblListNewArrayList();
    pblListAdd(in->_insideReceivers , in__0);
    out = (struct TypedIOPort*)TypedIOPort_New();
    #ifdef _debugging
    out->setName((struct IOPort*)out, "out");
    #endif
    out->container = (struct Actor*)DECGHeterogeneousMk2_ModalModel;
    out->_isInsideConnected = true;
    out->_isOutsideConnected = true;
    out->_isInput = false;
    out->_isOutput = true;
    out->_isMultiport = false;
    out->_width = 1;
    out->_insideWidth = 1;
    out->_numberOfSinks = 1;
    out->_numberOfSources = 0;
    out->_type = TYPE_Int;
    pblListAdd(DECGHeterogeneousMk2_ModalModel->_outputPorts, out);
    PblList* out_0 = pblListNewArrayList();
    struct FSMReceiver* out_0_0 = FSMReceiver_New();
    out_0_0->container = (struct IOPort*)out;
    pblListAdd(out_0, out_0_0);
    pblListAdd(out->_localInsideReceivers , out_0);
    PblList* out__0 = pblListNewArrayList();
    pblListAdd(out->_farReceivers, out__0);
    DECGHeterogeneousMk2_ModalModel__Director->container = DECGHeterogeneousMk2_ModalModel;
    DECGHeterogeneousMk2_ModalModel__Director->_startTime = 0.0;
    DECGHeterogeneousMk2_ModalModel__Director->_stopTime = Infinity;
    DECGHeterogeneousMk2_ModalModel__Director->localClock->container = (struct Director*)DECGHeterogeneousMk2_ModalModel__Director;
    DECGHeterogeneousMk2_ModalModel__Director->makeTransitions = DECGHeterogeneousMk2_ModalModel_makeTransitions;
    DECGHeterogeneousMk2_ModalModel__Director->transferModalInputs = DECGHeterogeneousMk2_ModalModel_transferModalInputs;
    DECGHeterogeneousMk2_ModalModel__Director->transferModalOutputs = DECGHeterogeneousMk2_ModalModel_transferModalOutputs;
    struct IOPort* DECGHeterogeneousMk2_ModalModel_state_in = (struct IOPort*)DECGHeterogeneousMk2_ModalModel_state_get_in();
    struct IOPort* DECGHeterogeneousMk2_ModalModel_state_out = (struct IOPort*)DECGHeterogeneousMk2_ModalModel_state_get_out();
    struct IOPort* DECGHeterogeneousMk2_ModalModel_state2_in = (struct IOPort*)DECGHeterogeneousMk2_ModalModel_state2_get_in();
    struct IOPort* DECGHeterogeneousMk2_ModalModel_state2_out = (struct IOPort*)DECGHeterogeneousMk2_ModalModel_state2_get_out();
    pblListAdd(pblListGet(DECGHeterogeneousMk2_ModalModel_state_out->_farReceivers, 0), pblListGet(pblListGet(out->_localInsideReceivers, 0), 0));
    pblListAdd(pblListGet(DECGHeterogeneousMk2_ModalModel_state2_out->_farReceivers, 0), pblListGet(pblListGet(out->_localInsideReceivers, 0), 0));
    pblListAdd(pblListGet(in->_insideReceivers, 0), pblListGet(pblListGet(DECGHeterogeneousMk2_ModalModel_state_in->_localReceivers, 0), 0));
    pblListAdd(pblListGet(in->_insideReceivers, 0), pblListGet(pblListGet(DECGHeterogeneousMk2_ModalModel_state2_in->_localReceivers, 0), 0));
    return DECGHeterogeneousMk2_ModalModel;
}
struct IOPort* DECGHeterogeneousMk2_ModalModel_get_in() {
    return (struct IOPort*) in;
}
struct IOPort* DECGHeterogeneousMk2_ModalModel_get_out() {
    return (struct IOPort*) out;
}
