/* Generated by Ptolemy II (http://ptolemy.eecs.berkeley.edu)
Copyright (c) 2005-2016 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.
IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS.
*/
#ifdef __cplusplus
extern "C" {
    #endif
    #include "DECGHeterogeneousMk2_DiscreteClock.h"
    #ifdef __cplusplus
}
#endif
/* Variable declaration code */
/* preinitDiscreteClock */
int DECGHeterogeneousMk2_DiscreteClock__phase;
Time DECGHeterogeneousMk2_DiscreteClock__period;
Time DECGHeterogeneousMk2_DiscreteClock__cycleStartTime;
Time DECGHeterogeneousMk2_DiscreteClock__stopTime;
int * DECGHeterogeneousMk2_DiscreteClock__values;
Time * DECGHeterogeneousMk2_DiscreteClock__offsets;
int DECGHeterogeneousMk2_DiscreteClock__offsetsNumber;
boolean DECGHeterogeneousMk2_DiscreteClock__enabled;
boolean DECGHeterogeneousMk2_DiscreteClock__triggered;
Time DECGHeterogeneousMk2_DiscreteClock__nextOutputTime;
int DECGHeterogeneousMk2_DiscreteClock__nextOutputIndex;
boolean DECGHeterogeneousMk2_DiscreteClock__outputProduced;
/* end variable declaration code */
#ifdef __cplusplus
extern "C" {
    #endif
    static struct TypedIOPort* output;
    void DECGHeterogeneousMk2_DiscreteClock_preinitialize(struct AtomicActor* actor);
    void DECGHeterogeneousMk2_DiscreteClock_initialize(struct AtomicActor* actor);
    bool DECGHeterogeneousMk2_DiscreteClock_prefire(struct AtomicActor* actor);
    void DECGHeterogeneousMk2_DiscreteClock_fire(struct AtomicActor* actor);
    bool DECGHeterogeneousMk2_DiscreteClock_postfire(struct AtomicActor* actor);
    void DECGHeterogeneousMk2_DiscreteClock_wrapup(struct AtomicActor* actor);
    struct AtomicActor* DECGHeterogeneousMk2_DiscreteClock_New() {
        struct AtomicActor* DECGHeterogeneousMk2_DiscreteClock = AtomicActor_New();
        #ifdef _debugging
        ((struct AtomicActor*)DECGHeterogeneousMk2_DiscreteClock)->setName((struct AtomicActor *)DECGHeterogeneousMk2_DiscreteClock, "DiscreteClock");
        #endif
        DECGHeterogeneousMk2_DiscreteClock->container = DECGHeterogeneousMk2;
        DECGHeterogeneousMk2_DiscreteClock->preinitialize = DECGHeterogeneousMk2_DiscreteClock_preinitialize;
        DECGHeterogeneousMk2_DiscreteClock->initialize = DECGHeterogeneousMk2_DiscreteClock_initialize;
        DECGHeterogeneousMk2_DiscreteClock->prefire = DECGHeterogeneousMk2_DiscreteClock_prefire;
        DECGHeterogeneousMk2_DiscreteClock->fire = DECGHeterogeneousMk2_DiscreteClock_fire;
        DECGHeterogeneousMk2_DiscreteClock->postfire = DECGHeterogeneousMk2_DiscreteClock_postfire;
        DECGHeterogeneousMk2_DiscreteClock->wrapup = DECGHeterogeneousMk2_DiscreteClock_wrapup;
        output = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        output->setName((struct IOPort*)output, "output");
        #endif
        output->container = (struct Actor*)DECGHeterogeneousMk2_DiscreteClock;
        output->_isInsideConnected = false;
        output->_isOutsideConnected = true;
        output->_isInput = false;
        output->_isOutput = true;
        output->_isMultiport = false;
        output->_width = 1;
        output->_insideWidth = 0;
        output->_numberOfSinks = 1;
        output->_numberOfSources = 0;
        output->_type = TYPE_Int;
        pblListAdd(DECGHeterogeneousMk2_DiscreteClock->_outputPorts, output);
        PblList* output__0 = pblListNewArrayList();
        pblListAdd(output->_farReceivers, output__0);
        return DECGHeterogeneousMk2_DiscreteClock;
    }
    struct IOPort* DECGHeterogeneousMk2_DiscreteClock_get_output() {
        return (struct IOPort*) output;
    }
    void DECGHeterogeneousMk2_DiscreteClock_preinitialize(struct AtomicActor* actor) {
        /* Preinitalization of the actor : DECGHeterogeneousMk2_DiscreteClock */
    }/* End of the preinitalization of the actor : DECGHeterogeneousMk2_DiscreteClock */
    void DECGHeterogeneousMk2_DiscreteClock_initialize(struct AtomicActor* actor) {
        /* Initalization of the actor : DECGHeterogeneousMk2_DiscreteClock */
        DECGHeterogeneousMk2_DiscreteClock__offsetsNumber = 1;
        DECGHeterogeneousMk2_DiscreteClock__offsets = calloc(1, sizeof(Time));
        DECGHeterogeneousMk2_DiscreteClock__offsets[0] = 0.0;
        DECGHeterogeneousMk2_DiscreteClock__values = calloc(1, sizeof(TYPE_Int));
        DECGHeterogeneousMk2_DiscreteClock__values[0] = 1;
        DECGHeterogeneousMk2_DiscreteClock__period = 1.0;
        DECGHeterogeneousMk2_DiscreteClock__phase = 0;
        DECGHeterogeneousMk2_DiscreteClock__enabled = true;
        DECGHeterogeneousMk2_DiscreteClock__triggered = true;
        DECGHeterogeneousMk2_DiscreteClock__outputProduced = false;
        DECGHeterogeneousMk2_DiscreteClock__stopTime = 10.0;
        struct Director* director = (*(actor->getDirector))(actor);
        DECGHeterogeneousMk2_DiscreteClock__cycleStartTime = (*(director->getModelTime))(director);
        DECGHeterogeneousMk2_DiscreteClock__nextOutputTime = DECGHeterogeneousMk2_DiscreteClock__cycleStartTime + DECGHeterogeneousMk2_DiscreteClock__offsets[DECGHeterogeneousMk2_DiscreteClock__phase];
        DECGHeterogeneousMk2_DiscreteClock__nextOutputIndex = 1;
        (*(director->fireAt))(director, (struct Actor*)actor, DECGHeterogeneousMk2_DiscreteClock__nextOutputTime, DECGHeterogeneousMk2_DiscreteClock__nextOutputIndex);
    }/* End of the initalization of the actor : DECGHeterogeneousMk2_DiscreteClock */
    bool DECGHeterogeneousMk2_DiscreteClock_prefire(struct AtomicActor* actor) {
        /* prefire of the actor : DECGHeterogeneousMk2_DiscreteClock */
        return true;
    }/* End of the prefire of the actor : DECGHeterogeneousMk2_DiscreteClock */
    #ifdef __cplusplus
}
#endif
void DECGHeterogeneousMk2_DiscreteClock_fire(struct AtomicActor* actor) {
    if (!DECGHeterogeneousMk2_DiscreteClock__enabled) {
        // if the clock is disabled
        return;
    }
    struct Director* director = (*(actor->getDirector))(actor);
    double comparison = DECGHeterogeneousMk2_DiscreteClock__nextOutputTime - (*(director->getModelTime))(director);
    if (comparison > 0) {
        return;
    } else if (comparison == 0) {
        // It is the right time to produce an output. Check
        // the index.
        if (DECGHeterogeneousMk2_DiscreteClock__nextOutputIndex > (*(((struct DEDirector*)director)->getMicrostep))((struct DEDirector*)director)) {
            // We have not yet reached the requisite index.
            // Request another firing at the current time.
            (*(director->fireAt))(director, (struct Actor*)actor, (*(director->getModelTime))(director),
            (*(((struct DEDirector*)director)->getMicrostep))((struct DEDirector*)director) + 1);
            return;
        }
        // At this point, the time matches the next output, and
        // the index either matches or exceeds the index for the next output,
        // or the director does not support superdense time.
        if (!DECGHeterogeneousMk2_DiscreteClock__triggered) {
            // Pretend we produced an output so that postfire() will
            // skip to the next phase.
            DECGHeterogeneousMk2_DiscreteClock__outputProduced = true;
            return;
        }
        // Ready to fire.
        if (DECGHeterogeneousMk2_DiscreteClock__enabled) {
            (*(output->send))((struct IOPort*) output, 0, Int_new(DECGHeterogeneousMk2_DiscreteClock__values[DECGHeterogeneousMk2_DiscreteClock__phase]));
            DECGHeterogeneousMk2_DiscreteClock__outputProduced = true;
        }
        return;
    }
}
#ifdef __cplusplus
extern "C" {
    #endif
    bool DECGHeterogeneousMk2_DiscreteClock_postfire(struct AtomicActor* actor) {
        /* Postfire of the actor : DECGHeterogeneousMk2_DiscreteClock */
        struct Director* director = (*(actor->getDirector))(actor);
        if ((*(director->getModelTime))(director) > DECGHeterogeneousMk2_DiscreteClock__stopTime) {
            return true;
        }
        if (DECGHeterogeneousMk2_DiscreteClock__outputProduced) {
            DECGHeterogeneousMk2_DiscreteClock__phase++;
            if (DECGHeterogeneousMk2_DiscreteClock__phase >= DECGHeterogeneousMk2_DiscreteClock__offsetsNumber) {
                DECGHeterogeneousMk2_DiscreteClock__phase = 0;
                DECGHeterogeneousMk2_DiscreteClock__cycleStartTime += DECGHeterogeneousMk2_DiscreteClock__period;
            }
            if (DECGHeterogeneousMk2_DiscreteClock__offsets[DECGHeterogeneousMk2_DiscreteClock__phase] > DECGHeterogeneousMk2_DiscreteClock__period) {
                perror("An offset of the Discrete Clock is greater than the period !");
                exit(1);
            }
            Time nextOutputTime = DECGHeterogeneousMk2_DiscreteClock__cycleStartTime + DECGHeterogeneousMk2_DiscreteClock__offsets[DECGHeterogeneousMk2_DiscreteClock__phase];
            if (DECGHeterogeneousMk2_DiscreteClock__nextOutputTime == nextOutputTime) {
                DECGHeterogeneousMk2_DiscreteClock__nextOutputIndex++;
            } else {
                DECGHeterogeneousMk2_DiscreteClock__nextOutputTime = nextOutputTime;
                DECGHeterogeneousMk2_DiscreteClock__nextOutputIndex = 1;
            }
            (*(director->fireAt))(director, (struct Actor*)actor, DECGHeterogeneousMk2_DiscreteClock__nextOutputTime,
            DECGHeterogeneousMk2_DiscreteClock__nextOutputIndex);
            DECGHeterogeneousMk2_DiscreteClock__outputProduced = false;
            if (false) {
                DECGHeterogeneousMk2_DiscreteClock__triggered = false;
            }
        }
        return true;
        return true;
    }/* End of the postfire of the actor : DECGHeterogeneousMk2_DiscreteClock */
    void DECGHeterogeneousMk2_DiscreteClock_wrapup(struct AtomicActor* actor) {
        /* Wrapup of the actor : DECGHeterogeneousMk2_DiscreteClock */
        /* wrapupDiscreteClock */
        free(DECGHeterogeneousMk2_DiscreteClock__values);
        free(DECGHeterogeneousMk2_DiscreteClock__offsets);
    }/* End of the wrapup of the actor : DECGHeterogeneousMk2_DiscreteClock */
    #ifdef __cplusplus
}
#endif
