/* Generated by Ptolemy II (http://ptolemy.eecs.berkeley.edu)
Copyright (c) 2005-2016 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.
IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS.
*/
#ifdef __cplusplus
extern "C" {
    #endif
    #include "DECGHeterogeneousMk2_Ramp.h"
    #ifdef __cplusplus
}
#endif
/* Variable declaration code */
/* preinitRamp */
int DECGHeterogeneousMk2_Ramp__state;
/* DECGHeterogeneousMk2_DE_Director's referenced parameter declarations. */
int DECGHeterogeneousMk2_Ramp_step_;
/* end variable declaration code */
#ifdef __cplusplus
extern "C" {
    #endif
    static struct TypedIOPort* trigger;
    static struct TypedIOPort* output;
    void DECGHeterogeneousMk2_Ramp_preinitialize(struct AtomicActor* actor);
    void DECGHeterogeneousMk2_Ramp_initialize(struct AtomicActor* actor);
    bool DECGHeterogeneousMk2_Ramp_prefire(struct AtomicActor* actor);
    void DECGHeterogeneousMk2_Ramp_fire(struct AtomicActor* actor);
    bool DECGHeterogeneousMk2_Ramp_postfire(struct AtomicActor* actor);
    void DECGHeterogeneousMk2_Ramp_wrapup(struct AtomicActor* actor);
    struct AtomicActor* DECGHeterogeneousMk2_Ramp_New() {
        struct AtomicActor* DECGHeterogeneousMk2_Ramp = AtomicActor_New();
        #ifdef _debugging
        ((struct AtomicActor*)DECGHeterogeneousMk2_Ramp)->setName((struct AtomicActor *)DECGHeterogeneousMk2_Ramp, "Ramp");
        #endif
        DECGHeterogeneousMk2_Ramp->container = DECGHeterogeneousMk2;
        DECGHeterogeneousMk2_Ramp->preinitialize = DECGHeterogeneousMk2_Ramp_preinitialize;
        DECGHeterogeneousMk2_Ramp->initialize = DECGHeterogeneousMk2_Ramp_initialize;
        DECGHeterogeneousMk2_Ramp->prefire = DECGHeterogeneousMk2_Ramp_prefire;
        DECGHeterogeneousMk2_Ramp->fire = DECGHeterogeneousMk2_Ramp_fire;
        DECGHeterogeneousMk2_Ramp->postfire = DECGHeterogeneousMk2_Ramp_postfire;
        DECGHeterogeneousMk2_Ramp->wrapup = DECGHeterogeneousMk2_Ramp_wrapup;
        trigger = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        trigger->setName((struct IOPort*)trigger, "trigger");
        #endif
        trigger->container = (struct Actor*)DECGHeterogeneousMk2_Ramp;
        trigger->_isInsideConnected = false;
        trigger->_isOutsideConnected = true;
        trigger->_isInput = true;
        trigger->_isOutput = false;
        trigger->_isMultiport = true;
        trigger->_width = 1;
        trigger->_insideWidth = 0;
        trigger->_numberOfSinks = 0;
        trigger->_numberOfSources = 1;
        trigger->_type = TYPE_Int;
        pblListAdd(DECGHeterogeneousMk2_Ramp->_inputPorts, trigger);
        PblList* trigger_0 = pblListNewArrayList();
        struct DEReceiver* trigger_0_0 = DEReceiver_New();
        trigger_0_0->container = (struct IOPort*)trigger;
        trigger_0_0->_director = (struct DEDirector*)(*(DECGHeterogeneousMk2_Ramp->getDirector))(DECGHeterogeneousMk2_Ramp);
        pblListAdd(trigger_0, trigger_0_0);
        pblListAdd(trigger->_localReceivers , trigger_0);
        output = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        output->setName((struct IOPort*)output, "output");
        #endif
        output->container = (struct Actor*)DECGHeterogeneousMk2_Ramp;
        output->_isInsideConnected = false;
        output->_isOutsideConnected = true;
        output->_isInput = false;
        output->_isOutput = true;
        output->_isMultiport = false;
        output->_width = 1;
        output->_insideWidth = 0;
        output->_numberOfSinks = 1;
        output->_numberOfSources = 0;
        output->_type = TYPE_Int;
        pblListAdd(DECGHeterogeneousMk2_Ramp->_outputPorts, output);
        PblList* output__0 = pblListNewArrayList();
        pblListAdd(output->_farReceivers, output__0);
        return DECGHeterogeneousMk2_Ramp;
    }
    struct IOPort* DECGHeterogeneousMk2_Ramp_get_trigger() {
        return (struct IOPort*) trigger;
    }
    struct IOPort* DECGHeterogeneousMk2_Ramp_get_output() {
        return (struct IOPort*) output;
    }
    void DECGHeterogeneousMk2_Ramp_preinitialize(struct AtomicActor* actor) {
        /* Preinitalization of the actor : DECGHeterogeneousMk2_Ramp */
        /* Ramp's parameter initialization */
        DECGHeterogeneousMk2_Ramp_step_ = 1;
    }/* End of the preinitalization of the actor : DECGHeterogeneousMk2_Ramp */
    void DECGHeterogeneousMk2_Ramp_initialize(struct AtomicActor* actor) {
        /* Initalization of the actor : DECGHeterogeneousMk2_Ramp */
        /* initialize Ramp */
        DECGHeterogeneousMk2_Ramp__state = 0;
        DECGHeterogeneousMk2_Ramp_step_ = 1;
    }/* End of the initalization of the actor : DECGHeterogeneousMk2_Ramp */
    bool DECGHeterogeneousMk2_Ramp_prefire(struct AtomicActor* actor) {
        /* prefire of the actor : DECGHeterogeneousMk2_Ramp */
        return true;
    }/* End of the prefire of the actor : DECGHeterogeneousMk2_Ramp */
    #ifdef __cplusplus
}
#endif
void DECGHeterogeneousMk2_Ramp_fire(struct AtomicActor* actor) {
    (*(output->send))((struct IOPort*) output, 0, Int_new(DECGHeterogeneousMk2_Ramp__state));
    if (false) {
        DECGHeterogeneousMk2_Ramp_step_ = Int_new(0)->payload.Int;
    }
    DECGHeterogeneousMk2_Ramp__state += (int)DECGHeterogeneousMk2_Ramp_step_;
}
#ifdef __cplusplus
extern "C" {
    #endif
    bool DECGHeterogeneousMk2_Ramp_postfire(struct AtomicActor* actor) {
        /* Postfire of the actor : DECGHeterogeneousMk2_Ramp */
        return true;
    }/* End of the postfire of the actor : DECGHeterogeneousMk2_Ramp */
    void DECGHeterogeneousMk2_Ramp_wrapup(struct AtomicActor* actor) {
        /* Wrapup of the actor : DECGHeterogeneousMk2_Ramp */
    }/* End of the wrapup of the actor : DECGHeterogeneousMk2_Ramp */
    #ifdef __cplusplus
}
#endif
