/* ptolemy.cg.kernel.generic.GenericCodeGenerator
Generated by Ptolemy II (http://ptolemy.eecs.berkeley.edu)
Copyright (c) 2005-2016 The Regents of the University of California.
All rights reserved.
Permission is hereby granted, without written agreement and without
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the above
copyright notice and the following two paragraphs appear in all copies
of this software.
IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS.
*/
#ifdef __cplusplus
extern "C" {
    #endif
    #include "DECGHelloWorld_Const.h"
    #ifdef __cplusplus
}
#endif
/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
Variable declaration code */
/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
end variable declaration code */
#ifdef __cplusplus
extern "C" {
    #endif
    static struct TypedIOPort* trigger;
    static struct TypedIOPort* output;
    void DECGHelloWorld_Const_preinitialize(struct AtomicActor* actor);
    void DECGHelloWorld_Const_initialize(struct AtomicActor* actor);
    bool DECGHelloWorld_Const_prefire(struct AtomicActor* actor);
    void DECGHelloWorld_Const_fire(struct AtomicActor* actor);
    bool DECGHelloWorld_Const_postfire(struct AtomicActor* actor);
    void DECGHelloWorld_Const_wrapup(struct AtomicActor* actor);
    struct AtomicActor* DECGHelloWorld_Const_New() {
        struct AtomicActor* DECGHelloWorld_Const = AtomicActor_New();
        #ifdef _debugging
        ((struct AtomicActor*)DECGHelloWorld_Const)->setName((struct AtomicActor *)DECGHelloWorld_Const, "Const");
        #endif
        DECGHelloWorld_Const->container = DECGHelloWorld;
        DECGHelloWorld_Const->preinitialize = DECGHelloWorld_Const_preinitialize;
        DECGHelloWorld_Const->initialize = DECGHelloWorld_Const_initialize;
        DECGHelloWorld_Const->prefire = DECGHelloWorld_Const_prefire;
        DECGHelloWorld_Const->fire = DECGHelloWorld_Const_fire;
        DECGHelloWorld_Const->postfire = DECGHelloWorld_Const_postfire;
        DECGHelloWorld_Const->wrapup = DECGHelloWorld_Const_wrapup;
        trigger = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        trigger->setName((struct IOPort*)trigger, "trigger");
        #endif
        trigger->container = (struct Actor*)DECGHelloWorld_Const;
        trigger->_isInsideConnected = false;
        trigger->_isOutsideConnected = true;
        trigger->_isInput = true;
        trigger->_isOutput = false;
        trigger->_isMultiport = true;
        trigger->_width = 1;
        trigger->_insideWidth = 0;
        trigger->_numberOfSinks = 0;
        trigger->_numberOfSources = 1;
        trigger->_type = TYPE_Double;
        pblListAdd(DECGHelloWorld_Const->_inputPorts, trigger);
        PblList* trigger_0 = pblListNewArrayList();
        struct DEReceiver* trigger_0_0 = DEReceiver_New();
        trigger_0_0->container = (struct IOPort*)trigger;
        trigger_0_0->_director = (struct DEDirector*)(*(DECGHelloWorld_Const->getDirector))(DECGHelloWorld_Const);
        pblListAdd(trigger_0, trigger_0_0);
        pblListAdd(trigger->_localReceivers , trigger_0);
        output = (struct TypedIOPort*)TypedIOPort_New();
        #ifdef _debugging
        output->setName((struct IOPort*)output, "output");
        #endif
        output->container = (struct Actor*)DECGHelloWorld_Const;
        output->_isInsideConnected = false;
        output->_isOutsideConnected = true;
        output->_isInput = false;
        output->_isOutput = true;
        output->_isMultiport = false;
        output->_width = 1;
        output->_insideWidth = 0;
        output->_numberOfSinks = 1;
        output->_numberOfSources = 0;
        output->_type = TYPE_String;
        pblListAdd(DECGHelloWorld_Const->_outputPorts, output);
        PblList* output__0 = pblListNewArrayList();
        pblListAdd(output->_farReceivers, output__0);
        return DECGHelloWorld_Const;
    }
    struct IOPort* DECGHelloWorld_Const_get_trigger() {
        return (struct IOPort*) trigger;
    }
    struct IOPort* DECGHelloWorld_Const_get_output() {
        return (struct IOPort*) output;
    }
    void DECGHelloWorld_Const_preinitialize(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Preinitalization of the actor : DECGHelloWorld_Const */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the preinitalization of the actor : DECGHelloWorld_Const */
    void DECGHelloWorld_Const_initialize(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Initalization of the actor : DECGHelloWorld_Const */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the initalization of the actor : DECGHelloWorld_Const */
    bool DECGHelloWorld_Const_prefire(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        prefire of the actor : DECGHelloWorld_Const */
        return true;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the prefire of the actor : DECGHelloWorld_Const */
    #ifdef __cplusplus
}
#endif
void DECGHelloWorld_Const_fire(struct AtomicActor* actor) {
    (*(output->send))((struct IOPort*) output, 0, String_new("Hello world!"));
}
#ifdef __cplusplus
extern "C" {
    #endif
    bool DECGHelloWorld_Const_postfire(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Postfire of the actor : DECGHelloWorld_Const */
        return true;
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the postfire of the actor : DECGHelloWorld_Const */
    void DECGHelloWorld_Const_wrapup(struct AtomicActor* actor) {
        /* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
        Wrapup of the actor : DECGHelloWorld_Const */
    }/* ptolemy.cg.kernel.generic.program.procedural.c.CCodeGenerator
    End of the wrapup of the actor : DECGHelloWorld_Const */
    #ifdef __cplusplus
}
#endif
